# Service: Adminer
#
# This service provides an Adminer container for database management via a web interface.
# It supports MySQL, PostgreSQL, SQLite, and other popular databases.
#
# See https://hub.docker.com/_/adminer/

services:
  adminer:
    container_name: ${PROJECT_NAME}_adminer
    environment:
      ADMINER_DESIGN: ${ADMINER_DESIGN:-pokorny}
    image: adminer:${ADMINER_VERSION:-latest}
    ports:
      - ${ADMINER_PORT:-8082}:8080
    restart: on-failure
