# Service: PHP
#
# This service provides a PHP-FPM container for backend applications.
# It supports PDO drivers and common extensions for frameworks like Laravel or Symfony.
#
# See https://hub.docker.com/_/php

services:
    php:
        build:
            context: ${PWD}/docker/application
            dockerfile: Dockerfile.php
            args:
                PHP_VERSION: ${PHP_VERSION:-latest}
        container_name: ${PROJECT_NAME}_php
        env_file:
            - ${PWD}/.env
        environment:
            COMPOSER_ROOT_VERSION: ${COMPOSER_ROOT_VERSION:-1.0.0}
        image: php:${PHP_VERSION:-latest}
        ports:
            - ${PHP_PORT:-9000}:9000
        restart: on-failure
        volumes:
            - ${PWD}/app/php:/usr/src/app:Z
