# Service: Apache
#
# This service provides an Apache HTTP Server container for serving PHP applications.
# It is typically used together with a PHP-FPM container as the web frontend.
#
# See https://httpd.apache.org/docs/

services:
  apache:
    build:
      context: ${PWD}/docker/infrastructure
      dockerfile: Dockerfile.apache
      args:
        APACHE_VERSION: ${APACHE_VERSION:-latest}
    container_name: ${PROJECT_NAME}_apache
    env_file:
      - ${PWD}/.env
    image: apache:${APACHE_VERSION:-latest}
    ports:
      - ${APACHE_PORT:-8081}:80
    restart: on-failure
    volumes:
      - ${PWD}/app:/var/www/html:Z
