# This service provides a minimal Apache container.
# It can be used to serve web applications or static content.

services:
  apache:
    build:
      context: ${PWD}/docker/infrastructure
      dockerfile: Dockerfile.apache
      args:
        APACHE_VERSION: ${APACHE_VERSION}
    container_name: ${PROJECT_NAME}_apache
    env_file:
      - ${PWD}/.env
    image: apache:${APACHE_VERSION}
    ports:
      - "${APACHE_PORT}:80"
    restart: on-failure
    volumes:
      - ${PWD}/app:/var/www/html:Z
