# Service: Nginx
#
# This service provides an Nginx container used as a lightweight web server or reverse proxy.
# Commonly used to serve static files or proxy requests to backend services such as PHP or Node.js.
#
# See https://nginx.org/en/docs/

services:
  nginx:
    build:
      context: ${PWD}/docker/infrastructure
      dockerfile: Dockerfile.nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION:-latest}
    container_name: ${PROJECT_NAME}_nginx
    env_file:
      - ${PWD}/.env
    image: nginx:${NGINX_VERSION:-latest}
    ports:
      - ${NGINX_PORT:-8080}:80
    restart: on-failure
    volumes:
      - ${PWD}/app:/var/www/html:Z
